# Generated by Django 2.0.4 on 2018-04-20 13:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviereview',
            name='movie_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='moviereview',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='moviereview',
            name='review',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
