# Generated by Django 2.0.4 on 2018-04-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20180420_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviereview',
            name='movie_title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
