# Generated by Django 2.0.4 on 2018-04-20 14:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0003_moviereview_movie_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviereview',
            name='user',
        ),
        migrations.AddField(
            model_name='moviereview',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Django Secure User'),
        ),
    ]
