# Generated by Django 2.0.4 on 2018-04-20 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0004_auto_20180420_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviereview',
            name='user',
        ),
        migrations.AddField(
            model_name='moviereview',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
