# Generated by Django 2.0.4 on 2018-04-25 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180425_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='static/images/logo.png', upload_to='static/images/useravi/'),
        ),
    ]
